name: Build

on: [push, pull_request]

jobs:
  install:

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-15, macos-26 ]
        package: [ libiio, libiio@1, libad9361-iio, iio-oscilloscope ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
    - name: Tap repository
      run: |
        brew tap tfcollins/formulae .
        brew trust tfcollins/formulae
    - name: Install
      env:
        HOMEBREW_NO_INSTALL_FROM_API: 1
      run: |
        [ "${{ matrix.package }}" != "libiio" ] && [ "${{ matrix.package }}" != "libiio@1" ] && brew install --verbose --build-from-source tfcollins/formulae/libiio
        [ "${{ matrix.package }}" == "iio-oscilloscope" ] && brew install --verbose --build-from-source tfcollins/formulae/libad9361-iio
        brew install --verbose --build-from-source tfcollins/formulae/${{ matrix.package }}
    - name: Test
      run: brew test tfcollins/formulae/${{ matrix.package }}
