name: Build

on: [push, pull_request]

jobs:
  install:

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-15 ]
        package: [ libiio, libad9361-iio, gr-iio, iio-oscilloscope ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Tap repository
      run: brew tap tfcollins/formulae .
    - name: Install
      env:
        HOMEBREW_NO_INSTALL_FROM_API: 1
      run: |
        [ "${{ matrix.package }}" == "gr-iio" ] && OPTIONS="--HEAD"
        [ "${{ matrix.package }}" != "libiio" ] && brew install --verbose --build-from-source tfcollins/formulae/libiio
        [ "${{ matrix.package }}" == "iio-oscilloscope" ] && brew install --verbose --build-from-source tfcollins/formulae/libad9361-iio
        [ "${{ matrix.package }}" == "iio-oscilloscope" ] && brew install --verbose --build-from-source tfcollins/formulae/gtkdatabox-prev1
        [ "${{ matrix.package }}" == "gr-iio" ] && brew install --verbose --build-from-source tfcollins/formulae/libad9361-iio
        brew install --verbose --build-from-source $OPTIONS tfcollins/formulae/${{ matrix.package }}
    - name: Test
      run: brew test tfcollins/formulae/${{ matrix.package }}
